# Generated by Django 3.2.9 on 2021-12-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=3000)),
                ('product_image', models.CharField(blank=True, max_length=5000, null=True)),
                ('product_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('product_price', models.PositiveIntegerField()),
                ('veg', models.BooleanField(blank=True, null=True)),
                ('nonveg', models.BooleanField(blank=True, null=True)),
                ('vegetarian', models.BooleanField(blank=True, null=True)),
                ('non_vegetarian', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
