# Generated by Django 3.2.9 on 2021-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211216_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGuy',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
