# Generated by Django 3.2.9 on 2021-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_deliveryguy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administratorrestaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='administratorrestaurant',
            name='employment_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='administratorrestaurant',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='administratorrestaurant',
            name='adress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administratorrestaurant',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='administratorrestaurant',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
