# Generated by Django 3.2.9 on 2021-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211228_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='veg',
            new_name='vegan',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
