# Generated by Django 3.2.9 on 2021-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211228_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_url',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
