# Generated by Django 3.2.9 on 2022-01-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211228_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeliveryGuy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.DeleteModel(
            name='AdministratorRestaurant',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
