# Generated by Django 3.2.9 on 2022-01-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_administratorrestaurant_customer_deliveryguy_menu_order_orderitem_product_restaurant_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
    ]
