# Generated by Django 3.2.9 on 2022-01-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
